### ISSUE TITLE
Data predating 1900

### ISSUE THREAD

**Issue by FelixNicol** [mbelvadi/library-journal-entitlements-project#264]
Hi,

There are entries predating 1900 in some spreadsheets. Here's an example in CRKN_PARightsTracking_WIL_2022_04_13_02_1.xlsx

<img width="790" alt="image" src="https://user-images.githubusercontent.com/98552762/202554210-d6cbcc5a-a6ba-42b1-8bfc-a3efb385470a.png">

It requires a little change in server/database/util/ingest-spreadsheets.php line 83:

```
          $yearInt = (int) $cells[$dbProperties->year]->getValue();
          if ($yearInt < 1900 || $yearInt > 2100) {
            fwrite($errorFile, "{$filename}\t{$rowIndex}\tinvalid year\n");
            continue;
          }
```

Thanks

Felix

**Comment by wavecommander** [comment]
#265 This pull request should fix the issue.

Here is a new release with that fix included:
https://github.com/mbelvadi/library-journal-entitlements-project/releases/tag/v1.0.4
